name: Context
on: [push, pull_request]

jobs:
  one:
    runs-on: ubuntu-latest
#    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        run: ${{ github.merges_url }}


