name: Takkoe
on: [push, pull_request]

jobs:
  one:
    runs-on: ubuntu-latest
#    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(secrets) }}
        run: echo "$GITHUB_CONTEXT"
      - name: test secrets
        run: ${{ toJson(secrets) }}


