name: Takkoe
on: [push, pull_request]

jobs:
  Taras-test:
    runs-on: ubuntu-latest
#    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub Secrets
        env:
          GITHUB_SECRETS: ${{ toJson(secrets) }}
        run: echo "$GITHUB_SECRETS"


